using RimWorld;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using UnityEngine;
using Verse;
using Random = System.Random;

namespace CellPrefabs
{
    internal class Dialog_CreateModSetting : Window
    {

        private const string PACKAGE_ID_SUFFIX = ".cellprefabs.buildings";
        private string customName = "";
        private string customPackageId = "";
        private string autoGeneratedName;
        private string autoGeneratedPackageId;
        private Action<string, string> onConfirmCallback;
        private Vector2 scrollPosition = Vector2.zero;

        public override Vector2 InitialSize => new Vector2(500, 300);

        public Dialog_CreateModSetting(Action<string, string> callback)
        {
            onConfirmCallback = callback;
            closeOnCancel = true;
            forcePause = true;
            absorbInputAroundWindow = true;
            doCloseX = true;
        }

        public override void DoWindowContents(Rect inRect)
        {
            Text.Font = GameFont.Medium;
            Widgets.Label(new Rect(inRect.x + 10, inRect.y + 10, inRect.width, 30), "设置Mod元数据");
            Text.Font = GameFont.Small;

            Rect contentRect = new Rect(inRect.x + 10, inRect.y + 50, inRect.width - 20, inRect.height - 60);
            Widgets.BeginScrollView(contentRect, ref scrollPosition, new Rect(0, 0, contentRect.width, 180));

            // 自动生成部分
            autoGeneratedName = GenerateAutoName();
            autoGeneratedPackageId = GenerateAutoPackageId();

            // Name字段 - 调整高度为35以容纳两行文本
            Widgets.Label(new Rect(0, 0, 120, 35), "模组名称(Mod Name):");
            customName = Widgets.TextField(new Rect(130, 0, 350, 35), customName.NullOrEmpty() ? autoGeneratedName : customName);
            if (Widgets.ButtonText(new Rect(490, 0, 80, 35), "生成")) // 按钮加宽以显示完整文本
            {
                customName = autoGeneratedName;
            }

            // PackageId字段 - 调整高度和位置
            Widgets.Label(new Rect(0, 50, 120, 35), "包名(PackageId):");

            // 调整前缀输入框宽度和高度
            Rect prefixRect = new Rect(130, 50, 100, 35); // 加宽输入框至200
            customPackageId = Widgets.TextField(prefixRect,
                customPackageId.NullOrEmpty() ? autoGeneratedPackageId.Split('.')[0] : customPackageId);

            // 后缀显示区域位置调整
            Rect suffixRect = new Rect(prefixRect.xMax + 5, 50, 150, 35); // 加宽后缀显示区域
            GUI.enabled = false;
            Widgets.TextField(suffixRect, PACKAGE_ID_SUFFIX);
            GUI.enabled = true;

            // 生成按钮位置和大小调整
            if (Widgets.ButtonText(new Rect(suffixRect.xMax + 5, 50, 100, 35), "生成(Random)")) // 加宽按钮
            {
                customPackageId = autoGeneratedPackageId;
            }

            Widgets.EndScrollView();

            // 确认按钮
            if (Widgets.ButtonText(new Rect(inRect.width / 2 - 75, inRect.height - 40, 150, 30), "Create Mod导出模组"))
            {
                if (ValidateInput())
                {
                    onConfirmCallback?.Invoke(customName, customPackageId+"."+ DateTime.Now.ToString("yyyyMMdd_HHmmss") +PACKAGE_ID_SUFFIX);
                    Close();
                }
            }
        }

        private bool ValidateInput()
        {
            if (customName.NullOrEmpty())
            {
                LogUtil.Message("Mod名称不能为空", MessageTypeDefOf.RejectInput);
                return false;
            }
            if (customPackageId.NullOrEmpty() || !IsValidPackageId(customPackageId))
            {
                LogUtil.Message("PackageId格式错误,只能输入字母数字和点，且点不能作为结尾", MessageTypeDefOf.RejectInput);
                return false;
            }
            return true;
        }

        private string GenerateAutoName()
        {
            string timestamp = DateTime.Now.ToString("yyyyMMdd_HHmmss");
            return $"CellPrefabs_UndefineName_{timestamp}";
        }

        private string GenerateAutoPackageId()
        {
            string randomStr = GenerateRandomString(6); // 使用原有随机函数
            return randomStr;
        }

        private bool IsValidPackageId(string id)
        {
            return Regex.IsMatch(id, @"^[a-zA-Z0-9_.]+(?<![.])$");
        }

        private static string GenerateRandomString(int length)
        {
            const string chars = "abcdefghijklmnopqrstuvwxyz";
            Random random = new Random();
            return new string(Enumerable.Repeat(chars, length)
              .Select(s => s[random.Next(s.Length)]).ToArray());
        }
    }

}
